### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by MatthijsBurgh** [mikepurvis/catkin_tools_document#12]
Could you create a new PyPi release?

**Comment by mikepurvis** [comment]
Sure! I think I'd like to get a story together for the epydoc -> pydoctor transition, but it's likely that can happen in the next few days.

**Comment by mikepurvis** [comment]
0.2.0 is on PyPI now, with py2 and py3 wheels:

https://pypi.org/project/catkin-tools-document/#history

Thanks for your contribution!
